site_name: BioMath Basic Docs Template
site_url: https://biomath-lab.github.io/basic_doc/
# logo: assets/favicon.ico
favicon: assets/favicon.ico

nav:
  - Home: 'pages/index.md'
  - About: 'pages/about.md'
  - Dissimilarity Cubes: 'pages/dissimilarity-cube.md'
  - Invasibility Cubes: 'pages/invasibility-cube.md'
  - Impact Indicators: 'pages/impact-indicators.md'

theme:
  name: material
  logo: assets/logo_sun.png
  nav_style: tabs
  nav:
    hide: true  # If available, this option might hide duplicates
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
      
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BioMath-Lab/basic_doc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xxxx
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/xxxxx

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg