site_name: BioMath Documents and Tutorials
site_url: https://biomath-lab.github.io/biomath-docs/

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Species Distribution Modelling: 'sdm.md'
  - Google Earth Engine: 'gee.md'
  - Other Resources: 'resources.md'

# nav:
#   - Home: 'index.md'
#   - 'User Guide':
#     - 'Writing your docs': 'writing-your-docs.md'
#     - 'Styling your docs': 'styling-your-docs.md'
#   - About:
#     - 'License': 'license.md'
#     - 'Release Notes': 'release-notes.md'

theme:
  name: material
  logo: assets/b3_logo.png
  features:
    # - navigation.instant
    # - navigation.instant.preview
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
      
# plugins:
#   - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 