site_name: BioMath Documents and Tutorials
site_url: https://biomath-lab.github.io/biomath-docs/

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Projects: 
      - Science-i: 'science-i.md'
  - Tutorials: 
      - Spatial R: 'spatial-r.md'
      - Species distribution modelling: 'sdm-r.md'
      - Google Earth Engine: 'gee-py.md'
      - Other resources: 'resources.md'
  - Dissimilarity Cubes: 'dissimilarity-cube.md'
  - Invasibility Cubes: 'invasibility-cube.md'
  - Impact Indicators: 'impact-indicators.md'

theme:
  name: material
  logo: assets/su_w2.png
  nav_style: tabs
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
      
extra:
  favicon: assets/favicon.ico
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BioMath-Lab/biomath-docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xxxx
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/xxxxx

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 
